/// <reference lib="webworker" />

// `$service-worker` is a SvelteKit-generated virtual module and is unavailable
// to standalone TypeScript language-service resolution.
// @ts-expect-error Generated by SvelteKit at build time.
import { build, files, prerendered, version } from '$service-worker';

const sw = self as unknown as ServiceWorkerGlobalScope;
const cacheName = `dawam-${version}`;
const assets = [
  ...new Set([...build, ...files, ...prerendered, '/', '/read/morning/', '/read/evening/']),
];

async function cacheAssets() {
  const cache = await caches.open(cacheName);

  await cache.addAll(assets);
}

async function activateCache() {
  for (const key of await caches.keys()) {
    if (key.startsWith('dawam-') && key !== cacheName) {
      await caches.delete(key);
    }
  }

  await sw.clients.claim();
}

async function serveRequest(request: Request) {
  const cache = await caches.open(cacheName);
  const url = new URL(request.url);
  const normalizedPath =
    url.pathname.startsWith('/read/') && !url.pathname.endsWith('/')
      ? url.pathname + '/'
      : url.pathname;

  const cachedResponse = await cache.match(normalizedPath);

  if (cachedResponse) {
    return cachedResponse;
  }

  try {
    return await fetch(request);
  } catch {
    return new Response('Anda sedang offline. Buka koleksi yang sudah tersimpan.', {
      status: 503,
      headers: { 'Content-Type': 'text/plain; charset=utf-8' },
    });
  }
}

sw.addEventListener('install', (event) => {
  event.waitUntil(cacheAssets());
});

sw.addEventListener('activate', (event) => {
  event.waitUntil(activateCache());
});

sw.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING') {
    sw.skipWaiting();
  }
});

sw.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET' || new URL(event.request.url).origin !== sw.location.origin) {
    return;
  }

  event.respondWith(serveRequest(event.request));
});
